name: Build Resume PDF and Deploy to Pages

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/build-resume.yml
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc, LaTeX and emoji fonts
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pandoc texlive-luatex texlive-latex-extra texlive-fonts-recommended \
            fonts-noto-color-emoji fonts-dejavu
          fc-cache -f

      - name: Set date
        run: echo "DATE_SUFFIX=$(date +'%m_%d_%Y')" >> "$GITHUB_ENV"

      - name: Build PDF (lualatex)
        run: |
          set -euo pipefail
          PDF_FILENAME="JP_Silva_Resume_${DATE_SUFFIX}.pdf"
          echo "Building $PDF_FILENAME"
          pandoc README.md \
            --pdf-engine=lualatex \
            -V fontsize=10pt \
            -o "$PDF_FILENAME"
          echo "PDF_ARTIFACT_NAME=$PDF_FILENAME" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf-${{ env.DATE_SUFFIX }}
          path: ${{ env.PDF_ARTIFACT_NAME }}
          retention-days: 90

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare Pages content
        run: |
          set -euo pipefail
          mkdir -p _artifact_to_deploy
          cp "${{ env.PDF_ARTIFACT_NAME }}" "_artifact_to_deploy/JP_Silva_Resume.pdf"
          echo "PDF_PAGES_DEPLOY_PATH=_artifact_to_deploy" >> "$GITHUB_ENV"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PDF_PAGES_DEPLOY_PATH }}

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Log URL
        if: success() && steps.deployment.outputs.page_url != ''
        run: |
          BASE_URL='${{ steps.deployment.outputs.page_url }}'
          case "$BASE_URL" in
            */) URL="${BASE_URL}JP_Silva_Resume.pdf" ;;
            *)  URL="${BASE_URL}/JP_Silva_Resume.pdf" ;;
          esac
          echo "Access: $URL"
